package stream.mediacontroller.websocket;

public enum Commands {
    // Audio
    AUDIO_INCREASE_MASTER_VOLUME,
    AUDIO_DECREASE_MASTER_VOLUME,

    // Config
    CONFIG_GET_CONFIG,

    // General
    GENERAL_GET_FILES_AND_FOLDERS,

    // Keyboard
    KEYBOARD_LOGIN,
    KEYBOARD_INPUT_STRING,
    KEYBOARD_PRESS_ENTER,
    KEYBOARD_FAST_NETFLIX_FORWARD,
    KEYBOARD_REWIND_NETFLIX_BACKWARD,
    KEYBOARD_NETFLIX_TOGGLE_PAUSE,
    KEYBOARD_NETFLIX_VOLUME_UP,
    KEYBOARD_NETFLIX_VOLUME_DOWN,
    KEYBOARD_NETFLIX_VOLUME_MUTE,

    // Mouse
    MOUSE_MOUSE_UP,
    MOUSE_MOUSE_DOWN,
    MOUSE_MOUSE_LEFT,
    MOUSE_MOUSE_RIGHT,
    MOUSE_LEFT_CLICK,
    MOUSE_NEXT_NETFLIX_EPISODE,
    MOUSE_SKIP_NETFLIX_INTRO,
//    MOUSE_FAST_NETFLIX_FORWARD,
//    MOUSE_REWIND_NETFLIX_BACKWARD,

    // Vlc
    VLC_PLAY_FILE,
    VLC_PLAY_FILES,
    VLC_STOP_MEDIA,
    VLC_PLAY_NEXT_MEDIA,
    VLC_PLAY_PREVIOUS_MEDIA,
    VLC_PAUSE_FILE,
    VLC_INCREASE_VOLUME,
    VLC_DECREASE_VOLUME,
    VLC_MUTE_VOLUME,
    VLC_FAST_FORWARD,
    VLC_REWIND,
    VLC_CYCLE_AUDIO_TRACK,
    VLC_CYCLE_SUBTITLE_TRACK

}