package stream.mediacontroller.websocket;

public enum Commands {
    MOUSE_UP,
    MOUSE_DOWN,
    MOUSE_LEFT,
    MOUSE_RIGHT,
    LEFT_CLICK,
    SKIP_NETFLIX_INTRO,
    NEXT_NETFLIX_EPISODE,
    FAST_NETFLIX_FORWARD,
    REWIND_NETFLIX_BACKWARD,
    GET_FILES_AND_FOLDERS,
    PLAY_FILE,
    GET_FULL_CONFIG,
    INCREASE_MASTER_VOLUME,
    DECREASE_MASTER_VOLUME
}