package stream.mediacontroller.websocket;

public enum Commands {
    // Audio
    AUDIO_INCREASE_MASTER_VOLUME,
    AUDIO_DECREASE_MASTER_VOLUME,

    // Config
    CONFIG_GET_CONFIG,

    // General
    GENERAL_GET_FILES_AND_FOLDERS,

    // Mouse
    MOUSE_MOUSE_UP,
    MOUSE_MOUSE_DOWN,
    MOUSE_MOUSE_LEFT,
    MOUSE_MOUSE_RIGHT,
    MOUSE_LEFT_CLICK,
    MOUSE_NEXT_NETFLIX_EPISODE,
    MOUSE_SKIP_NETFLIX_INTRO,
    MOUSE_FAST_NETFLIX_FORWARD,
    MOUSE_REWIND_NETFLIX_BACKWARD,

    // Vlc
    VLC_PLAY_FILE,
    VLC_PAUSE_FILE,

}